### PR TITLE
models added

### PR DESCRIPTION
**Pull request by samlanka**

### CODE REVIEW

**Comment by dselsam** [comment]
I like being to able to run all commands from the root directory. The `learning` imports work fine for me, but they don't work for @jesse-michael-han nor you for some reason. Are there things we can add that would allow this directory structure to work for you two? FYI I am using Python3.8.2.

**Comment by samlanka** [comment]
Have you tried without the learning imports? It should still run from the root directory.

**Comment by samlanka** [comment]
I moved all the models to learning/models

**Comment by dselsam** [comment]
Merged.

**Pull request closed without merging**
